#
frontend:

  #
  htmx: latest

  #
  hyperscript: latest

  #
  css:

    #
    framework: unocss
    version: latest

#
storage:

  #
  postgres:

    #
    self_hosted:
      container_name: gowebly-postgres
      version: latest
      user: '$POSTGRES_USER'
      password: '$POSTGRES_PASSWORD'
      database: '$POSTGRES_DATABASE'
      port: 5432

    #
    cloud:
      host: '$POSTGRES_HOST'
      user: '$POSTGRES_USER'
      password: '$POSTGRES_PASSWORD'
      database: '$POSTGRES_DATABASE'
      port: 5432
